POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iko0YnlyIiwiaWQiOiI2OGJkNjI2ZjFhMDBkMjMwNzMzNGNlZGYiLCJpYXQiOjE3NTc1ODk1ODd9.Kw_MPzUJgus4yKBpV1e9z4-HHwSeCq4pBv-2tjhQPyM

{
    "content":"Single page apps use token based auth",
    "important":false
}